/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as SummaryIndexRouteImport } from './routes/summary/index'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as DailyRoutinesIndexRouteImport } from './routes/daily-routines/index'
import { Route as DailyRoutinesCreateRouteImport } from './routes/daily-routines/create'
import { Route as TodosNewIndexRouteImport } from './routes/todos/new/index'
import { Route as GoalsNewIndexRouteImport } from './routes/goals/new/index'
import { Route as DailyRoutinesRoutineIdEditRouteImport } from './routes/daily-routines/$routineId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryIndexRoute = SummaryIndexRouteImport.update({
  id: '/summary/',
  path: '/summary/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoutinesIndexRoute = DailyRoutinesIndexRouteImport.update({
  id: '/daily-routines/',
  path: '/daily-routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoutinesCreateRoute = DailyRoutinesCreateRouteImport.update({
  id: '/daily-routines/create',
  path: '/daily-routines/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosNewIndexRoute = TodosNewIndexRouteImport.update({
  id: '/todos/new/',
  path: '/todos/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsNewIndexRoute = GoalsNewIndexRouteImport.update({
  id: '/goals/new/',
  path: '/goals/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoutinesRoutineIdEditRoute =
  DailyRoutinesRoutineIdEditRouteImport.update({
    id: '/daily-routines/$routineId/edit',
    path: '/daily-routines/$routineId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-routines/create': typeof DailyRoutinesCreateRoute
  '/daily-routines': typeof DailyRoutinesIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/summary': typeof SummaryIndexRoute
  '/todos': typeof TodosIndexRoute
  '/daily-routines/$routineId/edit': typeof DailyRoutinesRoutineIdEditRoute
  '/goals/new': typeof GoalsNewIndexRoute
  '/todos/new': typeof TodosNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-routines/create': typeof DailyRoutinesCreateRoute
  '/daily-routines': typeof DailyRoutinesIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/summary': typeof SummaryIndexRoute
  '/todos': typeof TodosIndexRoute
  '/daily-routines/$routineId/edit': typeof DailyRoutinesRoutineIdEditRoute
  '/goals/new': typeof GoalsNewIndexRoute
  '/todos/new': typeof TodosNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-routines/create': typeof DailyRoutinesCreateRoute
  '/daily-routines/': typeof DailyRoutinesIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/summary/': typeof SummaryIndexRoute
  '/todos/': typeof TodosIndexRoute
  '/daily-routines/$routineId/edit': typeof DailyRoutinesRoutineIdEditRoute
  '/goals/new/': typeof GoalsNewIndexRoute
  '/todos/new/': typeof TodosNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-routines/create'
    | '/daily-routines'
    | '/goals'
    | '/summary'
    | '/todos'
    | '/daily-routines/$routineId/edit'
    | '/goals/new'
    | '/todos/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-routines/create'
    | '/daily-routines'
    | '/goals'
    | '/summary'
    | '/todos'
    | '/daily-routines/$routineId/edit'
    | '/goals/new'
    | '/todos/new'
  id:
    | '__root__'
    | '/'
    | '/daily-routines/create'
    | '/daily-routines/'
    | '/goals/'
    | '/summary/'
    | '/todos/'
    | '/daily-routines/$routineId/edit'
    | '/goals/new/'
    | '/todos/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoutinesCreateRoute: typeof DailyRoutinesCreateRoute
  DailyRoutinesIndexRoute: typeof DailyRoutinesIndexRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  SummaryIndexRoute: typeof SummaryIndexRoute
  TodosIndexRoute: typeof TodosIndexRoute
  DailyRoutinesRoutineIdEditRoute: typeof DailyRoutinesRoutineIdEditRoute
  GoalsNewIndexRoute: typeof GoalsNewIndexRoute
  TodosNewIndexRoute: typeof TodosNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/': {
      id: '/summary/'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-routines/': {
      id: '/daily-routines/'
      path: '/daily-routines'
      fullPath: '/daily-routines'
      preLoaderRoute: typeof DailyRoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-routines/create': {
      id: '/daily-routines/create'
      path: '/daily-routines/create'
      fullPath: '/daily-routines/create'
      preLoaderRoute: typeof DailyRoutinesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/new/': {
      id: '/todos/new/'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/new/': {
      id: '/goals/new/'
      path: '/goals/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof GoalsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-routines/$routineId/edit': {
      id: '/daily-routines/$routineId/edit'
      path: '/daily-routines/$routineId/edit'
      fullPath: '/daily-routines/$routineId/edit'
      preLoaderRoute: typeof DailyRoutinesRoutineIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoutinesCreateRoute: DailyRoutinesCreateRoute,
  DailyRoutinesIndexRoute: DailyRoutinesIndexRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  SummaryIndexRoute: SummaryIndexRoute,
  TodosIndexRoute: TodosIndexRoute,
  DailyRoutinesRoutineIdEditRoute: DailyRoutinesRoutineIdEditRoute,
  GoalsNewIndexRoute: GoalsNewIndexRoute,
  TodosNewIndexRoute: TodosNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
